### ISSUE TITLE
[3.20.x]iOS build failed <> #import <SDWebImage/SDAnimatedImageView+WebCache.h> 

### ISSUE THREAD

**Issue by ivanichoo** [Appboy/appboy-react-sdk#68]
Hello,

iOS build failed with
- React SDK: 1.17.x 
- iOS SDK: 3.20.x
- React-Native: 0.59.9
- Pod: 1.7.5

Looks like SDWebImage 5.0 fail to link to the build...

All good for Android 👍 

Thanks!

-----
output:

The following build commands failed:
	CompileC /Users/ivanabrossimov/Documents/heroes/oly-app-united/ios/build/united-dev/Build/Intermediates.noindex/AppboyReactBridge.build/Debug-iphonesimulator/AppboyReactBridge.build/Objects-normal/x86_64/AppboyReactBridge.o /Users/ivanabrossimov/Documents/heroes/oly-app-united/node_modules/react-native-appboy-sdk/iOS/AppboyReactBridge/AppboyReactBridge/AppboyReactBridge.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

----

![Screenshot 2019-09-16 at 15 38 29](https://user-images.githubusercontent.com/1502196/64962649-11657080-d898-11e9-9b0f-cd9533f78ced.png)

**Comment by Bucimis** [comment]
@ivanichoo did you run `pod install`? is the `SDWebImage` framework present in the `Pods` directory of your application?

**Comment by ivanichoo** [comment]
Hello Jared,

I did run `pod install` (with a mandatory --repo-update).
SDWebImage is present in my Pods directory.

I went thru all updates and it is starting 1.13 react sdk and 3.15 ios sdk with the SDWebImage 5.0 when builds start to fail 🤔

**Comment by ivanichoo** [comment]
More logs: 

`In file included from /Users/ivanabrossimov/Documents/heroes/oly-app-united/node_modules/react-native-appboy-sdk/iOS/AppboyReactBridge/AppboyReactBridge/AppboyReactBridge.m:7:
In file included from ../../../../ios/Pods/Appboy-iOS-SDK/AppboyUI/ABKNewsFeed/ViewControllers/ABKNewsFeedViewController.h:2:
In file included from ../../../../ios/Pods/Appboy-iOS-SDK/AppboyUI/ABKNewsFeed/ViewControllers/ABKNewsFeedTableViewController.h:3:
../../../../ios/Pods/Appboy-iOS-SDK/AppboyUI/ABKNewsFeed/ViewControllers/Cells/ABKNFBaseCardCell.h:2:9: fatal error: 'SDWebImage/SDAnimatedImageView+WebCache.h' file not found
#import <SDWebImage/SDAnimatedImageView+WebCache.h>
`

**Comment by tomauty** [comment]
Having the same issue here. Tried a few things, nothing works.

**Comment by tomauty** [comment]
I've also tried adding the user-defined setting `$(APPBOY_LIBRARY_SEARCH_PATH)` to my xcworkspace and pointing it to all kinds of directories w/ no success :/

**Comment by Bucimis** [comment]
@ivanichoo @tomauty @cvlehe can you share the contents of your `Podfile.lock` (just lines relating to braze + sdwebimage is fine)? I want to ensure the latest version of SDWebImage was actually installed

**Comment by tomauty** [comment]
Sure!
```
PODS:
  - Amplitude-iOS (4.8.0)
  - Analytics (3.6.10)
  - Appboy-iOS-SDK (3.20.1):
    - Appboy-iOS-SDK/UI (= 3.20.1)
  - Appboy-iOS-SDK/ContentCards (3.20.1):
    - Appboy-iOS-SDK/Core
    - SDWebImage (~> 5.0)
  - Appboy-iOS-SDK/Core (3.20.1)
  - Appboy-iOS-SDK/InAppMessage (3.20.1):
    - Appboy-iOS-SDK/Core
    - SDWebImage (~> 5.0)
  - Appboy-iOS-SDK/NewsFeed (3.20.1):
    - Appboy-iOS-SDK/Core
    - SDWebImage (~> 5.0)
  - Appboy-iOS-SDK/UI (3.20.1):
    - Appboy-iOS-SDK/ContentCards
    - Appboy-iOS-SDK/Core
    - Appboy-iOS-SDK/InAppMessage
    - Appboy-iOS-SDK/NewsFeed
  - AppsFlyerFramework (4.10.4)
  - Button (6.15.0)
  - Charts (3.1.1):
    - Charts/Core (= 3.1.1)
  - Charts/Core (3.1.1)
  - SDWebImage (5.1.1):
    - SDWebImage/Core (= 5.1.1)
  - SDWebImage/Core (5.1.1)
  - Segment-Amplitude (2.0.0):
    - Amplitude-iOS (~> 4.0)
    - Analytics (~> 3.6)
  - Segment-Appboy (2.2.1):
    - Analytics (~> 3.0)
    - Segment-Appboy/Full-SDK (= 2.2.1)
  - Segment-Appboy/Full-SDK (2.2.1):
    - Analytics (~> 3.0)
    - Appboy-iOS-SDK (~> 3.20.1)
  - segment-appsflyer-ios (1.3.2):
    - Analytics (~> 3.5)
    - AppsFlyerFramework (= 4.10.4)
  - SwiftyJSON (4.2.0)

DEPENDENCIES:
  - Amplitude-iOS (~> 4.5)
  - Analytics (= 3.6.10)
  - Appboy-iOS-SDK (= 3.20.1)
  - AppsFlyerFramework
  - Button (= 6.15.0)
  - Charts (= 3.1.1)
  - Segment-Amplitude
  - Segment-Appboy
  - segment-appsflyer-ios
  - SwiftyJSON (= 4.2.0)

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - Amplitude-iOS
    - Analytics
    - Appboy-iOS-SDK
    - AppsFlyerFramework
    - Button
    - Charts
    - SDWebImage
    - Segment-Amplitude
    - Segment-Appboy
    - segment-appsflyer-ios
    - SwiftyJSON

SPEC CHECKSUMS:
  Amplitude-iOS: 2f704f85db0a6ded42cdeadb8aa0918d68019db1
  Analytics: 63744ad4afa65c3bcdcdb7a94b62515bde5b3900
  Appboy-iOS-SDK: 98c00597dafd00e3db6141e73e872b649fb8d7dd
  AppsFlyerFramework: aeb793095c1b33170ae30bef66652c0645f409be
  Button: 293c715efd628a84a613bab1bea755876d617942
  Charts: 90a4d61da0f6e06684c591e3bcab11940fe61736
  SDWebImage: 96d7f03415ccb28d299d765f93557ff8a617abd8
  Segment-Amplitude: bef43d0ec5c2986fe50c1e534e3d4db0171867f4
  Segment-Appboy: 53123a48b0e4075e76e604c3bc5ed8e5e5036cd3
  segment-appsflyer-ios: 5fba67663b1f9695a20f7a248dea948d06c4aa5f
  SwiftyJSON: c4bcba26dd9ec7a027fc8eade48e2c911f229e96

PODFILE CHECKSUM: ce326e26e5fb4e5585d49e789fa094fd48c656a3

COCOAPODS: 1.5.3
```

**Comment by cvlehe** [comment]
```
PODS:
  - Appboy-iOS-SDK (3.20.0):
    - Appboy-iOS-SDK/UI (= 3.20.0)
  - Appboy-iOS-SDK/ContentCards (3.20.0):
    - Appboy-iOS-SDK/Core
    - SDWebImage (~> 5.0)
  - Appboy-iOS-SDK/Core (3.20.0)
  - Appboy-iOS-SDK/InAppMessage (3.20.0):
    - Appboy-iOS-SDK/Core
    - SDWebImage (~> 5.0)
  - Appboy-iOS-SDK/NewsFeed (3.20.0):
    - Appboy-iOS-SDK/Core
    - SDWebImage (~> 5.0)
  - Appboy-iOS-SDK/UI (3.20.0):
    - Appboy-iOS-SDK/ContentCards
    - Appboy-iOS-SDK/Core
    - Appboy-iOS-SDK/InAppMessage
    - Appboy-iOS-SDK/NewsFeed
  - SDWebImage (5.1.1):
    - SDWebImage/Core (= 5.1.1)
  - SDWebImage/Core (5.1.1)

DEPENDENCIES:
  - Appboy-iOS-SDK (~> 3.20.0)

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - Appboy-iOS-SDK
    - SDWebImage

SPEC CHECKSUMS:
  Appboy-iOS-SDK: c7249a460a12ebcd9d4447da6ef90dd4f4b4f0ad
  SDWebImage: 96d7f03415ccb28d299d765f93557ff8a617abd8

PODFILE CHECKSUM: 1cc4e1e132cc4ce4477dffe7b56d558e64d96608

COCOAPODS: 1.6.1
```

**Comment by cvlehe** [comment]
I've also found commenting out:
```
#import "ABKNewsFeedViewController.h"
#import "ABKContentCardsViewController.h"
```

Allows me to compile at least.

**Comment by Bucimis** [comment]
@ivanichoo @cvlehe @tomauty thanks for the additional information. Things look good in terms of pod versions. Note that `AppboyReactBridge` needs to be able to see headers from `Appboy-iOS-SDK` as well as `SDWebImage`. I'd make sure the `AppboyReactBridge`'s header search paths (in Xcode->build settings) properly include the `Headers`, `Appboy-iOS-SDK`, and `SDWebImage` pod directories.

**Comment by tomauty** [comment]
As far as I can tell this is the proper setup:

<img width="1222" alt="Screen Shot 2019-09-16 at 4 49 35 PM" src="https://user-images.githubusercontent.com/1112872/64992497-044d7f00-d8a2-11e9-846c-6c7a405e2193.png">
<img width="1201" alt="Screen Shot 2019-09-16 at 4 49 30 PM" src="https://user-images.githubusercontent.com/1112872/64992498-044d7f00-d8a2-11e9-98f1-e802cc146fb2.png">

which unfortunately still has the issue :/

**Comment by Bucimis** [comment]
@tomauty could you try updating the `Pods/Headers/Public` in the first header search paths to just `Pods/Headers`?

**Comment by saraht129** [comment]
@Bucimis  I was facing the same issue and updating to iOS-SDK `3.20.1` and react native module to `1.17.1` seems to have resolved it. But I'm now seeing other errors around `SDWebImage`:

```
While building module 'Appboy_iOS_SDK' imported from /Users/sthian/Workstation/mobile-app/ios/RNBrazeInAppMessage.m:10:
While building module 'SDWebImage' imported from /Users/sthian/Library/Developer/Xcode/DerivedData/MoneyLion-fkbiuvmfaysopadapfytzhqespie/Build/Products/Debug-iphoneos/Appboy-iOS-SDK/Appboy_iOS_SDK.framework/Headers/ABKBannerContentCardCell.h:3:
In file included from <module-includes>:1:
In file included from /Users/sthian/Library/Developer/Xcode/DerivedData/MoneyLion-fkbiuvmfaysopadapfytzhqespie/Build/Products/Debug-iphoneos/SDWebImage/SDWebImage.framework/Headers/SDWebImage-umbrella.h:63:
/Users/sthian/Library/Developer/Xcode/DerivedData/MoneyLion-fkbiuvmfaysopadapfytzhqespie/Build/Products/Debug-iphoneos/SDWebImage/SDWebImage.framework/Headers/SDWebImage.h:10:9: error: include of non-modular header inside framework module 'SDWebImage.SDWebImage': '/Users/sthian/Library/Developer/Xcode/DerivedData/MoneyLion-fkbiuvmfaysopadapfytzhqespie/Build/Products/Debug-iphoneos/include/SDWebImage/SDWebImageCompat.h' [-Werror,-Wnon-modular-include-in-framework-module]
#import <SDWebImage/SDWebImageCompat.h>
        ^
```

and a lot of redefinition errors

```
While building module 'Appboy_iOS_SDK' imported from /Users/sthian/Workstation/mobile-app/ios/RNBrazeInAppMessage.m:10:
While building module 'SDWebImage' imported from /Users/sthian/Library/Developer/Xcode/DerivedData/MoneyLion-fkbiuvmfaysopadapfytzhqespie/Build/Products/Debug-iphoneos/Appboy-iOS-SDK/Appboy_iOS_SDK.framework/Headers/ABKBannerContentCardCell.h:3:
In file included from <module-includes>:1:
In file included from /Users/sthian/Library/Developer/Xcode/DerivedData/MoneyLion-fkbiuvmfaysopadapfytzhqespie/Build/Products/Debug-iphoneos/SDWebImage/SDWebImage.framework/Headers/SDWebImage-umbrella.h:63:
In file included from /Users/sthian/Library/Developer/Xcode/DerivedData/MoneyLion-fkbiuvmfaysopadapfytzhqespie/Build/Products/Debug-iphoneos/SDWebImage/SDWebImage.framework/Headers/SDWebImage.h:24:
In file included from /Users/sthian/Library/Developer/Xcode/DerivedData/MoneyLion-fkbiuvmfaysopadapfytzhqespie/Build/Products/Debug-iphoneos/include/SDWebImage/SDWebImageManager.h:11:
/Users/sthian/Library/Developer/Xcode/DerivedData/MoneyLion-fkbiuvmfaysopadapfytzhqespie/Build/Products/Debug-iphoneos/include/SDWebImage/SDWebImageDownloader.h:13:32: error: redefinition of 'SDWebImageDownloaderOptions'
typedef NS_OPTIONS(NSUInteger, SDWebImageDownloaderOptions) {

```

**Comment by Bucimis** [comment]
@saraht129 thanks for reporting.

A few things to try:
1) Delete your derived data folder and clean the build
2) Ensure that your project and `AppboyReactBridge` are pointing to the same SDWebImage pod directory (i.e. you dont have multiple instances of SDWebImage floating around your filesystem)
3) Delete your `Pods` folder and do a clean run of `pod install`

**Comment by gomdolkim** [comment]
to fix this problem as workaround, I had to change from `<SDWebImage/SDAnimatedImageView+WebCache.h>` to `"SDAnimatedImageView+WebCache.h"` after I add `../../../../ios/Pods/SDWebImage` and `../../../../ios/Pods/FLAnimatedImage` in `User Hader Search Paths`.

**Comment by Bucimis** [comment]
@gomdolkim what version of SDWebImage and the Appboy SDK are you using? `FLAnimatedImage` is no longer a dependency of the SDK as of 1.13.0 https://github.com/Appboy/appboy-react-sdk/blob/master/CHANGELOG.md#1130

**Comment by gomdolkim** [comment]
@Bucimis version is

**Comment by gomdolkim** [comment]
here are my Prodfile.lock and version of appboy-react-sdk is 1.17.1. @Bucimis 
```  
  - Appboy-iOS-SDK (3.20.1):
    - Appboy-iOS-SDK/UI (= 3.20.1)
  - Appboy-iOS-SDK/ContentCards (3.20.1):
    - Appboy-iOS-SDK/Core
    - SDWebImage (~> 5.0)
  - Appboy-iOS-SDK/Core (3.20.1)
  - Appboy-iOS-SDK/InAppMessage (3.20.1):
    - Appboy-iOS-SDK/Core
    - SDWebImage (~> 5.0)
  - Appboy-iOS-SDK/NewsFeed (3.20.1):
    - Appboy-iOS-SDK/Core
    - SDWebImage (~> 5.0)
  - Appboy-iOS-SDK/UI (3.20.1):
    - Appboy-iOS-SDK/ContentCards
    - Appboy-iOS-SDK/Core
    - Appboy-iOS-SDK/InAppMessage
    - Appboy-iOS-SDK/NewsFeed
  - FLAnimatedImage (1.0.12)
  - SDWebImage (5.1.1):
    - SDWebImage/Core (= 5.1.1)
  - SDWebImage/Core (5.1.1)
```

**Comment by gomdolkim** [comment]
The following solution worked for me. 

1. Upgrade Xcode to 10.3 otherwise you should turn off Bitcode on your app project
2. Update `react-native-appboy-sdk` to 1.17.1
3. Here is my Podfile. Without FLAnimatedImage I got the following error. actually I don't why the error was thrown. it might be only my case. if you don't get this error, you can remove `FLAnimatedImage` in pod. 
```
ld: framework not found FLAnimatedImage
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Here is my Podfile. 
```
target ‘MyApp’ do
  platform :ios, '9.0'
  pod 'Appboy-iOS-SDK', '~>3.20.0'
  pod 'FLAnimatedImage', '~> 1.0'
end
```

Here is my Podfile.lock
```
PODS:
  - Appboy-iOS-SDK (3.20.1):
    - Appboy-iOS-SDK/UI (= 3.20.1)
  - Appboy-iOS-SDK/ContentCards (3.20.1):
    - Appboy-iOS-SDK/Core
    - SDWebImage (~> 5.0)
  - Appboy-iOS-SDK/Core (3.20.1)
  - Appboy-iOS-SDK/InAppMessage (3.20.1):
    - Appboy-iOS-SDK/Core
    - SDWebImage (~> 5.0)
  - Appboy-iOS-SDK/NewsFeed (3.20.1):
    - Appboy-iOS-SDK/Core
    - SDWebImage (~> 5.0)
  - Appboy-iOS-SDK/UI (3.20.1):
    - Appboy-iOS-SDK/ContentCards
    - Appboy-iOS-SDK/Core
    - Appboy-iOS-SDK/InAppMessage
    - Appboy-iOS-SDK/NewsFeed
  - Crashlytics (3.14.0):
    - Fabric (~> 1.10.2)
  - Fabric (1.10.2)
  - FLAnimatedImage (1.0.12)
  - SDWebImage (5.1.1):
    - SDWebImage/Core (= 5.1.1)
  - SDWebImage/Core (5.1.1)

DEPENDENCIES:
  - Appboy-iOS-SDK (~> 3.20.0)
  - FLAnimatedImage (~> 1.0)

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - Appboy-iOS-SDK
    - FLAnimatedImage
    - SDWebImage
```

4. Delete Pods folder and Podfile.lock file
5. pod install in command
5. Go to AppboyReactBridge.xcodeproj then remove Path `../../../../ios/Pods/SDWebImage` if it exists.
6. Add `../../../../ios/Pods/SDWebImage` in Header Search Paths`
7. Change `<SDWebImage/SDAnimatedImageView+WebCache.h>` to `”SDAnimatedImageView+WebCache.h”` in the file you encountered compile error. 
8. Go to Pods project and select Appboy-iOS-SDK on TARGETS. 
9. Change `Enable Bitcode` from true to false
10. Run Archive again. then it will work

**Comment by gomdolkim** [comment]
The following solution worked for me. 

React SDK: 1.17.1
iOS SDK: 3.20.1
React-Native: 0.59.9

1. Upgrade Xcode to 10.3 otherwise you should turn off Bitcode on your app project
2. Update `react-native-appboy-sdk` to 1.17.1
3. Here is my Podfile. Without FLAnimatedImage I got the following error. actually I don't why the error was thrown. it might be only my case. if you don't get this error, you can remove `FLAnimatedImage` in pod. 
```
ld: framework not found FLAnimatedImage
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Here is my Podfile. 
```
target ‘MyApp’ do
  platform :ios, '9.0'
  pod 'Appboy-iOS-SDK', '~>3.20.0'
  pod 'FLAnimatedImage', '~> 1.0'
end
```

Here is my Podfile.lock
```
PODS:
  - Appboy-iOS-SDK (3.20.1):
    - Appboy-iOS-SDK/UI (= 3.20.1)
  - Appboy-iOS-SDK/ContentCards (3.20.1):
    - Appboy-iOS-SDK/Core
    - SDWebImage (~> 5.0)
  - Appboy-iOS-SDK/Core (3.20.1)
  - Appboy-iOS-SDK/InAppMessage (3.20.1):
    - Appboy-iOS-SDK/Core
    - SDWebImage (~> 5.0)
  - Appboy-iOS-SDK/NewsFeed (3.20.1):
    - Appboy-iOS-SDK/Core
    - SDWebImage (~> 5.0)
  - Appboy-iOS-SDK/UI (3.20.1):
    - Appboy-iOS-SDK/ContentCards
    - Appboy-iOS-SDK/Core
    - Appboy-iOS-SDK/InAppMessage
    - Appboy-iOS-SDK/NewsFeed
  - FLAnimatedImage (1.0.12)
  - SDWebImage (5.1.1):
    - SDWebImage/Core (= 5.1.1)
  - SDWebImage/Core (5.1.1)

DEPENDENCIES:
  - Appboy-iOS-SDK (~> 3.20.0)
  - FLAnimatedImage (~> 1.0)

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - Appboy-iOS-SDK
    - FLAnimatedImage
    - SDWebImage
```

4. Delete Pods folder and Podfile.lock file
5. pod install in command
5. Go to AppboyReactBridge.xcodeproj then remove Path `../../../../ios/Pods/SDWebImage` if it exists.
6. Add `../../../../ios/Pods/SDWebImage` in `Header Search Paths`
7. Change `<SDWebImage/SDAnimatedImageView+WebCache.h>` to `"SDAnimatedImageView+WebCache.h"` in the file you encountered compile error. 
8. Go to Pods project and select Appboy-iOS-SDK on TARGETS. 
9. Change `Enable Bitcode` from true to false
10. Run Archive again. then it will work

**Comment by ivanichoo** [comment]
> @ivanichoo @cvlehe @tomauty thanks for the additional information. Things look good in terms of pod versions. Note that `AppboyReactBridge` needs to be able to see headers from `Appboy-iOS-SDK` as well as `SDWebImage`. I'd make sure the `AppboyReactBridge`'s header search paths (in Xcode->build settings) properly include the `Headers`, `Appboy-iOS-SDK`, and `SDWebImage` pod directories.

Hello @Bucimis !

`Headers` and `SDWebImage` wasn't link in the `AppboyReactBridge` lib. It does build now! Thanks for your quick answer on this mandatory iOS13 update 😅 

Cheers! ✌️ 
 
-----

My podfile : 

> PODS:
>   - Appboy-iOS-SDK (3.20.1):
>     - Appboy-iOS-SDK/UI (= 3.20.1)
>   - Appboy-iOS-SDK/ContentCards (3.20.1):
>     - Appboy-iOS-SDK/Core
>     - SDWebImage (~> 5.0)
>   - Appboy-iOS-SDK/Core (3.20.1)
>   - Appboy-iOS-SDK/InAppMessage (3.20.1):
>     - Appboy-iOS-SDK/Core
>     - SDWebImage (~> 5.0)
>   - Appboy-iOS-SDK/NewsFeed (3.20.1):
>     - Appboy-iOS-SDK/Core
>     - SDWebImage (~> 5.0)
>   - Appboy-iOS-SDK/UI (3.20.1):
>     - Appboy-iOS-SDK/ContentCards
>     - Appboy-iOS-SDK/Core
>     - Appboy-iOS-SDK/InAppMessage
>     - Appboy-iOS-SDK/NewsFeed
>   - [...]
>   - SDWebImage (5.1.1):
>     - SDWebImage/Core (= 5.1.1)
>   - SDWebImage/Core (5.1.1)
> 
> DEPENDENCIES:
>   - Appboy-iOS-SDK (~> 3.20.1)
>     - [...]
> 
> SPEC REPOS:
>   https://github.com/cocoapods/specs.git:
>     - Appboy-iOS-SDK
>     - [...]
>     - SDWebImage
> 
> SPEC CHECKSUMS:
>   Appboy-iOS-SDK: 98c00597dafd00e3db6141e73e872b649fb8d7dd
>   [...]
>   SDWebImage: 96d7f03415ccb28d299d765f93557ff8a617abd8
> 
> PODFILE CHECKSUM: 6b1e2d1a8c275e1985f92032c2376f9b078a7eeb
> 
> COCOAPODS: 1.7.5

And `AppboyReactBridge` build settings : 

![Screenshot 2019-09-17 at 09 32 48](https://user-images.githubusercontent.com/1502196/65020786-21c82a80-d92e-11e9-8ecd-148a653c846b.png)

**Comment by saraht129** [comment]
@Bucimis to provide an update, I removed the duplicated `SDWebImage` instance, and am back to the `SDWebImage/SDAnimatedImageView+Webcache.h` file not found issue on `ABKNFBaseCardCell.h`. :/

**Comment by mlazari** [comment]
Having the same issue after updating:
 - `Appboy-iOS-SDK` from `3.8.4` to `3.20.1` (in pods);
 - `react-native-appboy-sdk` from `1.8.1` to `1.17.1` (linked manually).

It builds successfully if I change `$(SRCROOT)/../../../../ios/Pods/Appboy-iOS-SDK` to `$(SRCROOT)/../../../../ios/Pods` in `Libraries > AppboyReactBridge.xcodeproj > AppboyReactBridge target > Build Settings > Header Search Paths`, but this is obviously not a good solution, since that's in `node_modules` and it's not under version control.

I tried to verify what changed after update and the Header Search Paths are almost the same before and after update (only this changed: `APPBOY_LIBRARY_SEARCH_PATH` -> `$(APPBOY_LIBRARY_SEARCH_PATH)`, so maybe the root cause of the issue is not in this library, but can be fixed from it by adding the path to SDWebImage in Header Search Paths).

Btw, what exactly is `$(APPBOY_LIBRARY_SEARCH_PATH)`? Can we use it to insert a new header search path from the main app project, as a workaround? If yes, how?

**Comment by tomauty** [comment]
@mlazari I've tried using that before, but it's worth trying other paths to see if anything works. To add that setting, go to your project's Build Settings and add a user-defined setting:

<img width="646" alt="Screen Shot 2019-09-17 at 9 40 20 AM" src="https://user-images.githubusercontent.com/1112872/65046760-335e0200-d92f-11e9-888a-e0e7ffe87f76.png">

And add the path there that you would like. I'm not sure if it should be relative to the CWD of your project, or to the SRC_ROOT of the appboy sdk or what, though.

**Comment by tomauty** [comment]
I should say it did successfully build when I followed @gomdolkim's workaround:

> to fix this problem as workaround, I had to change from <SDWebImage/SDAnimatedImageView+WebCache.h> to "SDAnimatedImageView+WebCache.h" after I added ../../../../ios/Pods/SDWebImage and ../../../../ios/Pods/FLAnimatedImage in User Header Search Paths.

**Comment by mlazari** [comment]
@tomauty That doesn't work. I already tried with a user-defined setting, maybe I didn't specify the correct path. I used  `$(PODS_ROOT)/SDWebImage` as the value of that setting. I see now that it's set as non-recursive and tried `$(PODS_ROOT)/Headers/Public/SDWebImage`, still not working. Even tried replacing `$(PODS_ROOT)` with the absolute path from my computer and does not work.

**Comment by mlazari** [comment]
I just opened a PR for this issue: https://github.com/Appboy/appboy-react-sdk/pull/69
I'm not sure if that's the right fix (since it was working without it before), but it works for me.

**Comment by tomauty** [comment]
I'll give it a shot on our branch in a bit, thanks.

**Comment by tomauty** [comment]
Unfortunately no luck on our end. Will keep trying things.

**Comment by mlazari** [comment]
Maybe it's caused by some change in `SDWebImage` ? This one maybe - https://github.com/SDWebImage/SDWebImage/pull/2741 ?

**Comment by tomauty** [comment]
@mlazari Good call. Explicitly installing SDWebImage 5.0.6 in our Podfile let it build. I'm reverting other changes now to see if that's all it needed.

**Comment by tomauty** [comment]
Alright. Finally got it. Here's what I did:

1.) Explicitly include `SDWebImage` in Podfile. Here is most of our Podfile for the sake of being precise.
```
# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

# disable analytics
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'MoneyLion' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoneyLion
  pod 'Appboy-iOS-SDK', '3.20.1'
  pod 'SDWebImage', '5.0.6'
  target 'MoneyLionTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

2.) Build upon @mlazari 's patch by adding new paths to the Appboy bridge (will need PR or fork to keep that maintainable, but I don't see it being an issue to merge):

<img width="1174" alt="Screen Shot 2019-09-17 at 12 32 50 PM" src="https://user-images.githubusercontent.com/1112872/65061137-4977bc80-d947-11e9-9063-2d44cbe1041a.png">
<img width="1239" alt="Screen Shot 2019-09-17 at 12 32 46 PM" src="https://user-images.githubusercontent.com/1112872/65061138-4a105300-d947-11e9-9957-7ba0910b1099.png">

3.) Replace our local imports of `<Appboy-iOS-SDK/Appboykit.h>` (anything like that) with `"Appboykit.h"`.

**Comment by tomauty** [comment]
Opened #70 with our changes. Not sure if maintainers find that to be too brittle for general use, but thought I'd publish it anyway.

**Comment by changey** [comment]
experiencing the same issue with

React SDK: 1.17.x
iOS SDK: 3.20.x
React-Native: 0.59.9
Pod: 1.6.1

**Comment by mlazari** [comment]
@tomauty Thanks. I just tried your changes and it works for me without any other changes. I'm closing my PR.

**Comment by tomauty** [comment]
Now having issues with our CI/release builds, lol. Looking into that.

**Comment by ivanichoo** [comment]
Will this pod header path going to be patch soon for CIs? 👍

**Comment by changey** [comment]
Any update on merging the fix? Since this upgrade is recommended, thanks!

**Comment by Bucimis** [comment]
thanks @ivanichoo for raising and everyone for the discussion! we just released https://github.com/Appboy/appboy-react-sdk/releases/tag/1.17.3 which adds additional header search paths to our Appboy Bridge XCode project and should address this. Let us know how it goes!

**Comment by ivanichoo** [comment]
Working great now, CI's back to green! Thanks @Bucimis! ✅

**Comment by Bucimis** [comment]
Awesome thanks @ivanichoo et al! Feel free to re-raise if you run into any issues

**Comment by zhantx** [comment]
Hi @Bucimis ,
I still have this issue using 1.17.3. I integrated react-sdk manually, and put braze-ios-sdk in podfile

**Comment by cvlehe** [comment]
Also still having the same issue with `1.17.3` and Appboy-iOS-SDK `3.20.2`.

**Comment by mlazari** [comment]
`1.17.3` works for us. Also `appboy-react-sdk` linked manually and `Appboy-iOS-SDK 3.20.2` installed via Podfile.

**Comment by Bucimis** [comment]
@zhantx @cvlehe can you confirm the header search paths for your local `AppboyReactBridge` project point to the actual locations of the Appboy and SDWebImage pods installed in your project? Could you also post the specific errors you're seeing? Are they still related to importing SDWebImage?
